spring:
  application:
    name: customer_service
  datasource:
    password: ${DATABASE_PASSWORD:password}
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:customer_service}
    username: ${DATABASE_USER:default}
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
